added logs to details panel
felixmosh/bull-board pull request #210
Opened 2020-12-23 04:44 UTC by Jivings

2020-12-23 04:58 UTC, Jivings commented
fixes #97

2020-12-24 08:36 UTC, felixmosh requested changes

2020-12-24 08:36 UTC, felixmosh commented on src/queueAdapters/bull.ts
> +    return this.queue.getJobLogs(id).then(({logs}) => logs);
You have a lint issue here. pls fix

2020-12-24 08:36 UTC, felixmosh commented on src/queueAdapters/bullMQ.ts
> +    return this.queue.getJobLogs(id).then(({logs}) => logs);
You have a lint issue here. pls fix

2020-12-24 08:36 UTC, felixmosh commented on src/ui/components/Logs/Logs.tsx
> +  useEffect(() => {
Components should not know how to make AJAX requests, it breaks the entire encapsulation.
All "actions" are under `actions` object (which get passed already to JobCard).

This way you don't need to pass the queue name every where.

Pls refactor this 🙏🏼

2021-01-14 10:13 UTC, omairvaiyani commented
@Jivings need some help getting this over the line?

2021-01-15 02:34 UTC, Jivings commented
@omairvaiyani feel free to take over! I'm in a bad position where I can dedicate the time to fix my own issues but I'm not profecient in typescript, so I can't spend the extra time getting everything perfect.

Right now I have this running on a production bull instance for the last three weeks with no issues 👍

2021-03-22 13:15 UTC, closed without merging