Add truncate for large job's payload
felixmosh/bull-board pull request #414
Opened 2022-05-05 14:07 UTC by maxime-lenne

for this issue #413

2022-05-06 05:18 UTC, felixmosh commented
Thank you for this PR 🙏🏼
Can you add some images / payload example of the problem & the solution?

2022-05-06 08:03 UTC, maxime-lenne commented
Hi,

[large_payload.txt](https://github.com/felixmosh/bull-board/files/8638466/large_payload.txt)
![Capture d’écran 2022-05-06 à 09 41 22](https://user-images.githubusercontent.com/292328/167091970-19b54820-5ff9-4cc7-986d-1c47f2671684.png)
![Capture d’écran 2022-05-06 à 09 39 23](https://user-images.githubusercontent.com/292328/167091995-bede78ea-2dd0-4f9a-b844-b3d3dad3171a.png)

I have proposed this solution :

- limit string and array value to 10K characters
- limit the objects depth to 4
- up to this two limit replace the value of the json key with string : "[String-Truncated]", "[Array-Truncated]" or "[Object-Truncated]"

![Capture d’écran 2022-05-06 à 09 30 24](https://user-images.githubusercontent.com/292328/167092053-d42ff640-f799-4570-898c-686181c79b17.png)

2022-05-06 09:49 UTC, felixmosh requested changes

2022-05-06 09:49 UTC, felixmosh commented on packages/api/src/handlers/queues.ts
> +    Object.entries(dataToTruncate).forEach(([key, value]) => {
There is type change when value is 
1. `string` => 
 ```js 
 truncate('some-string') /* returns {
    "0": "s",
    "1": "o",
    "2": "m",
    "3": "e",
    "4": "-",
    "5": "s",
    "6": "t",
    "7": "r",
    "8": "i",
    "9": "n",
    "10": "g" */
}
```
3. `array` =>
 ```js 
 truncate([1,2,3]) /* returns {
    "0": 1,
    "1": 2,
    "2": 3
} */
```

2022-06-03 10:26 UTC, maxime-lenne commented
@felixmosh Thanks for this better way! I understand why you don't will to "hard coded" this.
May be document this formater feature for people that need like me to manipulate this fields and/or create an example. I try to do that when I'm less busy ;)

2022-06-03 10:26 UTC, closed without merging