Search functionality proposal
felixmosh/bull-board pull request #616
Opened 2023-08-08 15:33 UTC by CJSarao

Hi @felixmosh, this solution overloads the getAppQueues method a bit, let me know what you think and if you had something else in mind.. 

Also, since the newest release, I have typing errors when I try to test locally, I see that they were in the github action test as well on the last PR...

- The search functionality keeps the number of jobs per page and scales the number of pages accordingly. 
- Search is done with onBlur on the textfield, so clicking away or pressing enter triggers the search. 
- Search is looking at job ids and data properties, could add more values if needed
- Retry all and clean all actions are still shown even if the jobs are filtered, but still affect all of the jobs (not only the filtered ones)
->Is this ideal behavior? 
->Should the bulk actions be hidden if we're filtering or should they affect only the filtered jobs?

2023-08-10 18:13 UTC, CJSarao commented
Hey, waiting for feedback on the proposed solution before I pull the most recent changes and address conflicts

2023-08-13 07:08 UTC, felixmosh commented on packages/api/src/handlers/queues.ts
> +      const isFiltered:Boolean = query.searchPrompt;
if it should be boolean, it should be something like:
```js
const isFiltered= Boolean(query.searchPrompt);
// or
const isFiltered= !!query.searchPrompt;
```

2023-08-13 08:06 UTC, felixmosh requested changes

2023-08-13 08:06 UTC, felixmosh commented on packages/api/src/handlers/queues.ts
> +          ? await queue.getJobs(status)
There is any other way to search the data in Redis or something like this?
I think that fetching all jobs in order to filter them out is not efficient.

2023-08-13 08:06 UTC, felixmosh commented
Hi @CJSarao, thanx for this PR, as search feature is really required by others, let's see the best options to implement it properly.

2023-08-16 03:06 UTC, CJSarao commented
Hey @felixmosh, thanks for your review! I agree with most of your suggestions. 

As to why I needed to persist the value, it felt the best UX wise for my needs in my use case of the library. I see no problem with not storing it. 

> There is any other way to search the data in Redis or something like this?
I think that fetching all jobs in order to filter them out is not efficient.

Regarding that, I'm not aware of bull/bullmq exposing this capability, did you mean for this library to interact with redis directly? My understanding is that we're already polling the full list pretty regularly, which is why I wasn't too concerned with efficiency.. I'd like to understand what you have in mind, not always easy with async messages haha

2023-08-16 04:08 UTC, felixmosh commented
We are mot pulling all the list... It gets pagination on the redis sode.

I've opened a feature request in bullmq, hope that they will help.

2023-08-16 20:41 UTC, CJSarao commented
> We are mot pulling all the list... It gets pagination on the redis sode.
> 
> I've opened a feature request in bullmq, hope that they will help.

That's right, good point. Keep me posted I'd be glad to work on this some more and make it better!

2023-08-19 16:39 UTC, felixmosh commented
https://github.com/taskforcesh/bullmq/issues/2135

2024-01-04 07:07 UTC, closed without merging