Added support for AdonisJS v6
felixmosh/bull-board pull request #838
Opened 2024-10-15 18:40 UTC by atharahmed

This PR adds an adapter for AdonisJS v6 and tries to solve [#797](https://github.com/felixmosh/bull-board/issues/797)

2024-10-16 08:02 UTC, felixmosh requested changes

2024-10-16 08:02 UTC, felixmosh commented on packages/adonis/src/AdonisAdapter.ts
> +    this.errorHandler = handler;
I don't see that there is any usage of this errorHandler from Adonis part... did you missed it?

2024-10-16 08:02 UTC, felixmosh commented
Hi @atharahmed thank you for this awasom PR 🙏🏽

2024-10-16 12:34 UTC, atharahmed commented on packages/adonis/package.json
> +    "ts-node-maintained": "^10.9.4"
My apologies, I have removed the `ts-node-maintained`.

2024-10-16 12:41 UTC, atharahmed commented on packages/adonis/src/AdonisAdapter.ts
> +          const statics = this.statics;
I have looked into the `@adonisjs/static` and docs here: https://docs.adonisjs.com/guides/basics/static-file-server#static-files-server, but they haven't shared any way to use the static file server beyond the config. It seems to only load static build assets from the `public` folder, so I found an example of `fs` in `packages > h3 > H3Adapter.ts` and implemented that instead.

I also needed to use the `mime` package to find the right `Content-Type` header to return to render the file correctly.

I will continue to explore Adonis's codebase to see if I can find a way to use the static file server.

2024-10-17 08:16 UTC, felixmosh commented on packages/adonis/src/AdonisAdapter.ts
> +          const statics = this.statics;
h3 package has several checks inorder to prevent path traversal Issue.
Maybe you can implement somthing similar.

2025-01-24 03:59 UTC, closed without merging

2025-05-03 11:02 UTC, mGGk-fr commented
Hey 👋 

Do you think this can be re-opened and merged or does it needs anything else ?